[package]
name = "histutils"
version = "1.0.0"
edition = "2024"
rust-version = "1.86"
description = "Import, export or merge zsh extended or fish history files."
license = "MIT"
readme = "README.md"

[lib]
name = "histutils"
path = "src/lib.rs"

[[bin]]
name = "histutils"
path = "src/main.rs"
